services:
  redis:
    build:
      context: redis
    ports:
      - 6379:6379
    volumes:
      - dbfleet-bitnami-redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${DBFLEET_REDIS_PASSWORD}
  postgres:
    image: "timescale/timescaledb-postgis:latest-pg12" # Warning: Deploy at your own risk!
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DBFLEET_POSTGRES_PASSWORD}
    volumes:
      - dbfleet-postgres-tspg:/var/lib/postgresql/data
