services:
  redis:
    build:
      context: redis
    ports:
      - 6379:6379
    volumes:
      - dbfleet-bitnami-redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${DBFLEET_REDIS_PASSWORD}
  postgres:
    image: "timescale/timescaledb-postgis:latest-pg12" # Warning: Deploy at your own risk!
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DBFLEET_POSTGRES_PASSWORD}
    volumes:
      - dbfleet-postgres-tspg:/var/lib/postgresql/data

volumes:
  dbfleet-bitnami-redis:
    driver_opts:
      size: 512Mi
  dbfleet-postgres-tspg:
    driver_opts:
      size: 1Gi

# Since these ports don't autmatically made public for security reasons,
# we need to use endpoints here.
endpoints:
  redis-dbfleet1:
    - path: /
      service: redis
      port: 6379
  postgres-dbfleet1:
    - path: /
      service: postgres
      port: 5432